kafka:
  host: localhost
  port: 9092

sources:
  dir: ./data
  files:
  - synthetic_financial_datasets.csv

streamer:
  messages_per_second: 1

logs:
  dir: ./logs
  info_file: info.log
  warning_file: info.log
  error_file: error.log
  critical_file: error.log
  debug_file: debug.log
