cassandra:
  host: localhost
  port: 9042

kafka:
  host: localhost
  port: 9092

redis:
  host: localhost
  port: 6379
  db: 0

sources:
  dir: ./data

streamer:
  - file: synthetic_financial_datasets.csv
    topic: sfd
    redis_key: streamer1_active
    messages_per_second: 1
    sleep_disabled: 10

logs:
  dir: ./logs
  info_file: info.log
  warning_file: info.log
  error_file: error.log
  critical_file: error.log
  debug_file: debug.log
