version: '3.1'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    networks:
      - streamer-net
  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    environment:
      NAME: redis
    networks:
      - streamer-net
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - streamer-net
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: localhost
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - streamer-net
  #kafka-ui:
    #container_name: kafka-ui
    #image: provectuslabs/kafka-ui:latest
    #ports:
      #- 8080:8080
    #environment:
      #DYNAMIC_CONFIG_ENABLED: true
    #volumes:
      #- ./data/kui/config.yaml:/etc/kafkaui/dynamic_config.yaml
    #networks:
      #- streamer-net
networks:
  streamer-net:
    name: streamer-net
    driver: bridge
