{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Fraud Detector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fraud Confidence over time",
   "type": "heatmap",
   "description": "Show fraud confidence over time for each bank",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "SELECT bank_id, CAST(fraud_confidence AS DOUBLE) as fraud_confidence, timestamp FROM fraud_detection.transactions_by_bank\n"
    }
   ]
  },
  {
   "title": "Average Fraud Confidence ",
   "type": "gauge",
   "description": "Show average fraud confidence for each bank",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "SELECT bank_id, CAST(fraud_confidence AS DOUBLE) as fraud_confidence, timestamp FROM fraud_detection.transactions_by_bank\n"
    }
   ]
  },
  {
   "title": "Transactions over time",
   "type": "stat",
   "description": "Show transactions number over time for each bank",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "target": "SELECT bank_id, amount, timestamp FROM fraud_detection.transactions_by_bank\n"
    }
   ]
  },
  {
   "title": "Transactions proportion for each bank",
   "type": "piechart",
   "description": "Show transactions proportion over time for each bank",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "target": "SELECT bank_id, amount, timestamp FROM fraud_detection.transactions_by_bank\n"
    }
   ]
  },
  {
   "title": "Transactions proportion for account type",
   "type": "piechart",
   "description": "Show transactions proportion over time for each account type",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "target": "SELECT account_type, amount, timestamp FROM fraud_detection.transactions_by_bank\n"
    }
   ]
  },
  {
   "title": "Fraud proportion for account type",
   "type": "piechart",
   "description": "Show frauds proportion over time for each account type",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "target": "SELECT account_type, amount, timestamp FROM fraud_detection.transactions_by_bank where is_fraud = true ALLOW FILTERING\n"
    }
   ]
  },
  { "title": "Streamer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Streamer 1 - Status",
   "type": "gauge",
   "description": "Status of Streamer 1",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "get", "keyName": "streamer1.active", "type": "command" }
   ]
  },
  {
   "title": "Streamer 2 - Status",
   "type": "gauge",
   "description": "Status of Streamer 2",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "get", "keyName": "streamer2.active", "type": "command" }
   ]
  }
 ]
}